server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #          uri: git@github.com:pengwei-x/spring-cloud-config-center.git #GitHub上面的git仓库名字
          uri: https://github.com/pengwei-x/spring-cloud-config-center.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - spring-cloud-config-center
      ####读取分支
      label: main
#rabbitmq相关配置
rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'


